GET http://localhost:4000/users/

###

DELETE http://localhost:4000/users/6374912fe6f7e60338cfd3c4

###

GET http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "jtester2002@gmail.com",
    "password": "verysecurepassword"
}

###

POST http://localhost:4000/users/create
Content-Type: application/json

{
    "name": "Moe Tester",
    "username": "mtester2002",
    "email": "mtester2002@gmail.com",
    "password": "verysecurepassword",
    "bio": "Very skilled individual",
    "skills": ["C++", "Java"]
}

###

GET http://localhost:4000/users/6374912fe6f7e60338cfd3c4
Content-Type: application/json

###

PUT http://localhost:4000/users/6374912fe6f7e60338cfd3c4
Content-Type: application/json

{
    "field": "skills",
    "content": ["C++", "Java"]
}

######################################################################

GET http://localhost:4000/projects/

###

DELETE http://localhost:4000/projects/63756d3afffc51284ca25e0d

###

GET http://localhost:4000/projects/homepage
Content-Type: application/json

{
    "userId": "63756a08cded4b52ec7c165d"
}

### 

PUT http://localhost:4000/projects/swiperight
Content-Type: application/json

{
    "projectId": "637aba5ea1f3323f58512f0d",
    "userId": "63756a08cded4b52ec7c165d"
}

### 

PUT http://localhost:4000/projects/swipeleft
Content-Type: application/json

{
    "projectId": "63756d3afffc51284ca25e0d",
    "userId": "63756a08cded4b52ec7c165d"
}

###
POST http://localhost:4000/projects/create
Content-Type: application/json

{
    "title": "Fitness App",
    "description": "Track your workouts",
    "skillset": ["C++", "Java"],
    "timeline": "3 months",
    "creator": "6375665d12675b2ff4af2405"
}

###
GET http://localhost:4000/projects/createdprojects
Content-Type: application/json

{
    "userId": "6375665d12675b2ff4af2405"
}

###
PUT http://localhost:4000/projects/check
Content-Type: application/json

{
    "userId": "63756a08cded4b52ec7c165d",
    "projectId": "637aba5ea1f3323f58512f0d"
}

###
PUT http://localhost:4000/projects/uncheck
Content-Type: application/json

{
    "userId": "63756a08cded4b52ec7c165d",
    "projectId": "637aba5ea1f3323f58512f0d"
}