GET http://localhost:4000/api/users/

###

DELETE http://localhost:4000/api/users/6374912fe6f7e60338cfd3c4

###

GET http://localhost:4000/api/users/login?email=prashant2@test.com&password=test

###

POST http://localhost:4000/api/users/create
Content-Type: application/json

{
    "name": "Moe Tester",
    "username": "mtester2002",
    "email": "mtester2002@gmail.com",
    "password": "verysecurepassword",
    "bio": "Very skilled individual",
    "skills": ["C++", "Java"]
}

###

GET http://localhost:4000/api/users/63823c924a0de95cddc54052

###

PUT http://localhost:4000/api/users/6374912fe6f7e60338cfd3c4
Content-Type: application/json

{
    "field": "skills",
    "content": ["C++", "Java"]
}

######################################################################

GET http://localhost:4000/api/projects/

###
GET http://localhost:4000/api/projects/createdprojects?userId=63824360149a7a6b1f4eea69

###

DELETE http://localhost:4000/api/projects/63756d1cfffc51284ca25e02

###

GET http://localhost:4000/api/projects/63824654ed8f6d6f567dbbc9

###

GET http://localhost:4000/api/projects/homepage?userId=63824654ed8f6d6f567dbbc9

### 

PUT http://localhost:4000/api/projects/swiperight
Content-Type: application/json

{
    "projectId": "63756d1cfffc51284ca25e02",
    "userId": "63756a08cded4b52ec7c165d"
}

### 

PUT http://localhost:4000/api/projects/swipeleft
Content-Type: application/json

{
    "projectId": "63756d3afffc51284ca25e0d",
    "userId": "63756a08cded4b52ec7c165d"
}

###
POST http://localhost:4000/api/projects/create
Content-Type: application/json

{
    "title": "Fitness App",
    "description": "Track your workouts",
    "skillset": ["C++", "Java"],
    "timeline": "3 months",
    "creator": "6375665d12675b2ff4af2405"
}